### PR TITLE
set limit for postgres dialect

### PR DESCRIPTION
**Pull request by cramja**
Found potentially the correct spot to add our LIMIT clause.

related: https://www.pivotaltracker.com/story/show/163074105

### CODE REVIEW

**Comment by cramja** [comment]
tested in dev, this appears to have worked

https://grafana.au-infrastructure.com/d/Ghby1lUiz/kafka-connect-service?refresh=1m&panelId=19&fullscreen&edit&orgId=1&from=1547567770571&to=1547568415978

**Review by menendezau — APPROVED** [review]
Cool beans

**Comment by akasprzok** [comment]
I have no idea what this does, but I trust in Mr. Menendez.

**Comment by cramja** [comment]
👍 @akasprzok it makes all your problems go away

**Pull request merged**
